//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("SelfMailer", "MailServerSender", "MailServer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SelfMailer.Entities.MailServer), "Sender", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SelfMailer.Entities.Sender))]

#endregion

namespace SelfMailer.Entities
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class SelfMailerContainer : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet SelfMailerContainer à l'aide de la chaîne de connexion trouvée dans la section 'SelfMailerContainer' du fichier de configuration d'application.
        /// </summary>
        public SelfMailerContainer() : base("name=SelfMailerContainer", "SelfMailerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet SelfMailerContainer.
        /// </summary>
        public SelfMailerContainer(string connectionString) : base(connectionString, "SelfMailerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet SelfMailerContainer.
        /// </summary>
        public SelfMailerContainer(EntityConnection connection) : base(connection, "SelfMailerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<MailServer> MailServers
        {
            get
            {
                if ((_MailServers == null))
                {
                    _MailServers = base.CreateObjectSet<MailServer>("MailServers");
                }
                return _MailServers;
            }
        }
        private ObjectSet<MailServer> _MailServers;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Sender> Senders
        {
            get
            {
                if ((_Senders == null))
                {
                    _Senders = base.CreateObjectSet<Sender>("Senders");
                }
                return _Senders;
            }
        }
        private ObjectSet<Sender> _Senders;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet MailServers. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMailServers(MailServer mailServer)
        {
            base.AddObject("MailServers", mailServer);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Senders. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSenders(Sender sender)
        {
            base.AddObject("Senders", sender);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SelfMailer", Name="MailServer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(WithAuthentification))]
    [KnownTypeAttribute(typeof(WithoutAuthentification))]
    public partial class MailServer : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet MailServer.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="host">Valeur initiale de la propriété Host.</param>
        public static MailServer CreateMailServer(global::System.Int32 id, global::System.String host)
        {
            MailServer mailServer = new MailServer();
            mailServer.ID = id;
            mailServer.Host = host;
            return mailServer;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Host
        {
            get
            {
                return _Host;
            }
            set
            {
                OnHostChanging(value);
                ReportPropertyChanging("Host");
                _Host = StructuralObject.SetValidValue(value, false, "Host");
                ReportPropertyChanged("Host");
                OnHostChanged();
            }
        }
        private global::System.String _Host;
        partial void OnHostChanging(global::System.String value);
        partial void OnHostChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SelfMailer", "MailServerSender", "Sender")]
        public EntityCollection<Sender> Sender
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sender>("SelfMailer.MailServerSender", "Sender");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sender>("SelfMailer.MailServerSender", "Sender", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SelfMailer", Name="Sender")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sender : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Sender.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="name">Valeur initiale de la propriété Name.</param>
        /// <param name="email">Valeur initiale de la propriété Email.</param>
        public static Sender CreateSender(global::System.Int32 id, global::System.String name, global::System.String email)
        {
            Sender sender = new Sender();
            sender.ID = id;
            sender.Name = name;
            sender.Email = email;
            return sender;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SelfMailer", "MailServerSender", "MailServer")]
        public EntityCollection<MailServer> MailServer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MailServer>("SelfMailer.MailServerSender", "MailServer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MailServer>("SelfMailer.MailServerSender", "MailServer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SelfMailer", Name="WithAuthentification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WithAuthentification : MailServer
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet WithAuthentification.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="host">Valeur initiale de la propriété Host.</param>
        /// <param name="username">Valeur initiale de la propriété Username.</param>
        /// <param name="password">Valeur initiale de la propriété Password.</param>
        public static WithAuthentification CreateWithAuthentification(global::System.Int32 id, global::System.String host, global::System.String username, Password password)
        {
            WithAuthentification withAuthentification = new WithAuthentification();
            withAuthentification.ID = id;
            withAuthentification.Host = host;
            withAuthentification.Username = username;
            withAuthentification.Password = StructuralObject.VerifyComplexObjectIsNotNull(password, "Password");
            return withAuthentification;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false, "Username");
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();

        #endregion

        #region Propriétés complexes
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmComplexPropertyAttribute()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [XmlElement(IsNullable=true)]
        [SoapElement(IsNullable=true)]
        [DataMemberAttribute()]
        public Password Password
        {
            get
            {
                _Password = GetValidValue(_Password, "Password", false, _PasswordInitialized);
                _PasswordInitialized = true;
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = SetValidValue(_Password, value, "Password");
                _PasswordInitialized = true;
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private Password _Password;
        private bool _PasswordInitialized;
        partial void OnPasswordChanging(Password value);
        partial void OnPasswordChanged();

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SelfMailer", Name="WithoutAuthentification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WithoutAuthentification : MailServer
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet WithoutAuthentification.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="host">Valeur initiale de la propriété Host.</param>
        public static WithoutAuthentification CreateWithoutAuthentification(global::System.Int32 id, global::System.String host)
        {
            WithoutAuthentification withoutAuthentification = new WithoutAuthentification();
            withoutAuthentification.ID = id;
            withoutAuthentification.Host = host;
            return withoutAuthentification;
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SelfMailer", Name="Password")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Password : ComplexObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Password.
        /// </summary>
        /// <param name="value">Valeur initiale de la propriété Value.</param>
        /// <param name="allowSave">Valeur initiale de la propriété AllowSave.</param>
        public static Password CreatePassword(global::System.String value, global::System.Boolean allowSave)
        {
            Password password = new Password();
            password.Value = value;
            password.AllowSave = allowSave;
            return password;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false, "Value");
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AllowSave
        {
            get
            {
                return _AllowSave;
            }
            set
            {
                OnAllowSaveChanging(value);
                ReportPropertyChanging("AllowSave");
                _AllowSave = StructuralObject.SetValidValue(value, "AllowSave");
                ReportPropertyChanged("AllowSave");
                OnAllowSaveChanged();
            }
        }
        private global::System.Boolean _AllowSave;
        partial void OnAllowSaveChanging(global::System.Boolean value);
        partial void OnAllowSaveChanged();

        #endregion

    }

    #endregion

}
